name: Deploy pipeline

on:
  push:
    branches: ["main"]
    paths:
      - '**.py'
      - 'serialized/**'
      - 'Dockerfile'

jobs:
  Deployment:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3

      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and export to Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: bus_routes_bot
      -
        name: Push Docker image
        run: |
          docker tag bus_routes_bot eugeneparkhom/bus_routes_bot:1.0.${{ github.run_number }}
          docker push eugeneparkhom/bus_routes_bot:1.0.${{ github.run_number }}
    